# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "000_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ram.github.io/nbdev_exp/"

git_url = "https://github.com/ram/nbdev_exp/tree/master/"

def custom_doc_links(name): return None
