# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/031_HPsearch.ipynb (unless otherwise specified).

__all__ = ['TASK_NAME']

# Cell
from .HeteroData_synthesize import run_simulation
from clearml import Task
from random import sample
from datetime import datetime

TASK_NAME = "HP searching"